FROM docker.io/paritytech/ci-linux:production as builder
#FROM parity/substrate:latest


RUN apt update 
RUN apt-get install -y supervisor
RUN apt-get install -y tmux
RUN apt-get install -y curl
RUN apt-get install -y wget
RUN apt-get install -y python3
RUN apt-get install -y python3-setuptools
RUN pip3 install Flask
RUN pip3 install substrateinterface
RUN cargo install keccak256-cli

ADD scripts/qdao_services.sh /bin/qdao_services.sh 

RUN mkdir /opt/data

RUN echo "Downloading git repo..."
RUN if [ -d "/opt/data/QRUCIAL-DAO" ]; then \
  echo "QRUCIAL-DAO exists"; \
  ( cd /opt/data/QRUCIAL-DAO && git pull https://github.com/Qrucial/QRUCIAL-DAO.git ); \
  else \
  ( cd /opt/data/ && git clone https://github.com/Qrucial/QRUCIAL-DAO.git ); \
  fi


RUN echo "Compiling exosys..."
RUN if [ ! -f "/opt/data/QRUCIAL-DAO/exosysd/target/release/qdao-exosysd" ]; then \
  ( cd /opt/data/QRUCIAL-DAO/exosysd && cargo build --release ); \
  fi

RUN echo "Compiling qdao-node..."
RUN if [ ! -f "/opt/data/QRUCIAL-DAO/qdao-node/target/release/qdao-node" ]; then \
  ( cd /opt/data/QRUCIAL-DAO/qdao-node && cargo build --release ); \
  fi

#RUN ls -la /opt/data/QRUCIAL-DAO/qdao-node/target/release/qdao-node 1>&2
#RUN ls -la /opt/data/QRUCIAL-DAO/exosysd/target/release 1>&2

RUN chmod +x /opt/data/QRUCIAL-DAO/qdao-node/target/release/qdao-node
RUN chmod +x /opt/data/QRUCIAL-DAO/exosysd/target/release/qdao-exosysd

# Q2 - Add some sort of healthcheck
# HEALTHCHECK 

RUN chmod +x /bin/qdao_services.sh
ENTRYPOINT ["/bin/qdao_services.sh"]
