FROM docker.io/paritytech/ci-linux:production as builder
#FROM parity/substrate:latest


RUN apt update 
RUN apt-get install -y supervisor
RUN apt-get install -y tmux
RUN apt-get install -y curl
RUN apt-get install -y wget
RUN apt-get install -y python3
RUN cargo install keccak256-cli

ADD scripts/qdao_services.sh /bin/qdao_services.sh 

ADD ./data /opt/data
RUN mkdir /opt/testing

RUN echo "downloading git repo..."
RUN if [ -d "/opt/data/QRUCIAL-DAO" ]; then \
  echo "QRUCIAL-DAO exists"; \
  ( cd /opt/data/QRUCIAL-DAO && git pull https://github.com/Qrucial/QRUCIAL-DAO.git ); \
  else \
  ( cd /opt/data/ && git clone https://github.com/Qrucial/QRUCIAL-DAO.git ); \
  fi


RUN echo "compileing qdao-node..."
#RUN ( cd /opt/data/QRUCIAL-DAO/qdao-node && cargo build --release )
RUN if [ ! -f "/opt/data/QRUCIAL-DAO/exosysd/target/release/qdao-exosysd" ]; then \
  ( cd /opt/data/QRUCIAL-DAO/qdao-node && cargo build --release ); \
  fi

RUN echo "compileing exosysd"
RUN if [ ! -f "/opt/data/QRUCIAL-DAO/qdao-node/target/release/qdao-node" ]; then \
  ( cd /opt/data/QRUCIAL-DAO/exosysd && cargo build --release ); \
  fi

#RUN ( cd /opt/data/QRUCIAL-DAO/exosysd/ && cargo build --release ) 

RUN chmod +x /opt/data/QRUCIAL-DAO/exosysd/target/release/qdao-exosysd
RUN chmod +x /opt/data/QRUCIAL-DAO/qdao-node/target/release/qdao-node

# Q2 - Add some sort of healthcheck
# HEALTHCHECK 

RUN chmod +x /bin/qdao_services.sh
ENTRYPOINT ["/bin/qdao_services.sh"]
