FROM rust:buster

RUN cargo install cargo-audit # install cargo audit

# This will always return success, it normally fails after update (we just need update)
RUN cargo audit -db || : 
RUN echo "Ignore Error above. just used to sync repo"

RUN mkdir /usr/exotools/
ADD ./scripts/audit_script.sh /usr/exotools/
RUN chmod +x /usr/exotools/audit_script.sh
# Figure out a check we can do to make sure the container is running nominaly.
# for the pallets having it send a ping without failing would work,
# for exotools we dont really need one yet, as they get deployed and then shut down.
# HEALTHCHECK # ping 0.0.0.0

#ENTRYPOINT ["ls"]
ENTRYPOINT ["/usr/exotools/audit_script.sh"]
# This is a not great solution but it works
