FROM rust:buster

RUN apt update 
RUN apt-get install -y python3-pip graphviz xdg-utils
RUN cargo install cargo-audit

# This will always return success, it normally fails after update (we just need update)
RUN cargo audit -db || : 
RUN echo "Ignore Error above. just used to sync repo"

# Prepare to run the off-chain automated audit
RUN mkdir /usr/exotools/
ADD ./scripts/audit_script.sh /usr/exotools/
RUN chmod +x /usr/exotools/audit_script.sh

# This starts the off-chain automated auditing
ENTRYPOINT ["/usr/exotools/audit_script.sh"]